### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by Scrappers-glitch** [2Math0/phonebook-mobile-flutter#15]
For the sake of clean code, i suggest using the conventional naming across `packages`, `classes` and `variables` or `instances`.

So, 
- For classes : use `CamelCase` also known as `PascalCase` with a first uppercase letter.

- For packages : favor nested packages on a combined name package and if you have to use a combined name then `lowercase` for all letters is good.
Example : favor `com.java.util.io.streams` on `com.javautil.io.streams`.

- For variables : use `camelCase` with a first lowercase letter.

And classes should be of the same name as the files holding them so those files should be renamed for example :
- https://github.com/2Math0/phonebook-mobile-flutter/blob/ec955b3924414a08086064e957eaab050c689b14/lib/widgets/dotted_Field.dart#L5
- https://github.com/2Math0/phonebook-mobile-flutter/blob/ec955b3924414a08086064e957eaab050c689b14/lib/widgets/login_input_field.dart#L5
- Others
If some files don't use classes like cpp, try to introduce classes to them, classes create a clean scoped code, if this is not accessible then following `CamelCase` naming for .dart files would be sufficient.

**Comment by 2Math0** [comment]
actually, I had some classes whose names didn't describe their nature only their usage which can be inconvenient in further development 
but for the Camel Casing issue, Dart has its own Naming convention.
I highly suggest to check this [link](https://dart.dev/guides/language/effective-dart/style) that has more illustration about the topic
