### ISSUE TITLE
Build a calling Ui

### ISSUE THREAD

**Issue by Scrappers-glitch** [2Math0/phonebook-mobile-flutter#16]
When trying to call someone from the `ContactsList`, the conca app redirects me to my Contacts app, i think its better to build your own calling service Ui and backend using a `ConnectionService`.

Check those things out using `Platform Specific Channel` : 
https://learn.vonage.com/blog/2021/03/18/make-app-to-phone-call-using-android-and-flutter/
https://docs.flutter.dev/development/platform-integration/platform-channels?tab=android-channel-java-tab

You can add this to a future milestone or something.

**Comment by 2Math0** [comment]
It's a good future but it has its own risks with different Android Systems therefore we had to drop it down for now
